In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [5]:
data = pd.read_csv('./data/행정안전부_지역별(행정동)_성별_주민등록_인구증감_20240930.csv', encoding='cp949')
data

,행정기관코드,기준연월,시도명,시군구명,읍면동명,전체 전월인구수,전월 남자인구수,전월 여자인구수,전체 당월인구수,당월 남자인구수,당월 여자인구수,전체 인구증감,남자 인구증감,여자 인구증감
0,1111051500,2024-09-30,서울특별시,종로구,청운효자동,11177,5093,6084,11143,5079,6064,-34,-14,-20
1,1111053000,2024-09-30,서울특별시,종로구,사직동,8993,3951,5042,8995,3948,5047,2,-3,5
2,1111054000,2024-09-30,서울특별시,종로구,삼청동,2229,1067,1162,2234,1073,1161,5,6,-1
3,1111055000,2024-09-30,서울특별시,종로구,부암동,9071,4256,4815,9054,4255,4799,-17,-1,-16
4,1111056000,2024-09-30,서울특별시,종로구,평창동,17231,7983,9248,17232,7987,9245,1,4,-3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3609,5280038000,2024-09-30,전북특별자치도,부안군,백산면,2343,1170,1173,2336,1163,1173,-7,-7,0
3610,5280039000,2024-09-30,전북특별자치도,부안군,상서면,2056,1023,1033,2047,1021,1026,-9,-2,-7
3611,5280040000,2024-09-30,전북특별자치도,부안군,하서면,2374,1173,1201,2374,1174,1200,0,1,-1
3612,5280041000,2024-09-30,전북특별자치도,부안군,줄포면,2438,1201,1237,2430,1203,1227,-8,2,-10
3613,5280042000,2024-09-30,전북특별자치도,부안군,위도면,1098,610,488,1090,605,485,-8,-5,-3

In [6]:
data['행정기관코드'].dtype

dtype('int64')

In [7]:
data['행정기관코드'] = data['행정기관코드'].astype(str)

In [8]:
data['행정기관코드'].dtype

dtype('O')

In [9]:
# '행정기관코드'의 앞 2자리가 '41'인 것만 남기고 data에 덮어쓰기
data = data[data['행정기관코드'].str.startswith('41')]

# 결과 확인
data

,행정기관코드,기준연월,시도명,시군구명,읍면동명,전체 전월인구수,전월 남자인구수,전월 여자인구수,전체 당월인구수,당월 남자인구수,당월 여자인구수,전체 인구증감,남자 인구증감,여자 인구증감
1200,4111156000,2024-09-30,경기도,수원시 장안구,파장동,24935,12596,12339,24855,12547,12308,-80,-49,-31
1201,4111156600,2024-09-30,경기도,수원시 장안구,율천동,40018,21206,18812,40038,21219,18819,20,13,7
1202,4111157100,2024-09-30,경기도,수원시 장안구,정자1동,33277,16281,16996,33382,16341,17041,105,60,45
1203,4111157200,2024-09-30,경기도,수원시 장안구,정자2동,38477,18844,19633,38503,18857,19646,26,13,13
1204,4111157300,2024-09-30,경기도,수원시 장안구,정자3동,39093,19542,19551,39054,19531,19523,-39,-11,-28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1798,4183037000,2024-09-30,경기도,양평군,청운면,3751,1944,1807,3748,1938,1810,-3,-6,3
1799,4183038000,2024-09-30,경기도,양평군,양동면,4529,2292,2237,4518,2286,2232,-11,-6,-5
1800,4183039500,2024-09-30,경기도,양평군,지평면,6715,3426,3289,6688,3411,3277,-27,-15,-12
1801,4183040000,2024-09-30,경기도,양평군,용문면,18762,9432,9330,18720,9414,9306,-42,-18,-24
1802,4183041000,2024-09-30,경기도,양평군,개군면,5115,2613,2502,5100,2606,2494,-15,-7,-8

In [10]:
data['기준연월'].dtype

dtype('O')

In [12]:
data['기준연월'] = pd.to_datetime(data['기준연월'], format='%Y-%m-%d').dt.to_period('M')

C:\Users\5-04\AppData\Local\Temp\ipykernel_16380\1826034331.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['기준연월'] = pd.to_datetime(data['기준연월'], format='%Y-%m-%d').dt.to_period('M')

In [13]:
data

,행정기관코드,기준연월,시도명,시군구명,읍면동명,전체 전월인구수,전월 남자인구수,전월 여자인구수,전체 당월인구수,당월 남자인구수,당월 여자인구수,전체 인구증감,남자 인구증감,여자 인구증감
1200,4111156000,2024-09,경기도,수원시 장안구,파장동,24935,12596,12339,24855,12547,12308,-80,-49,-31
1201,4111156600,2024-09,경기도,수원시 장안구,율천동,40018,21206,18812,40038,21219,18819,20,13,7
1202,4111157100,2024-09,경기도,수원시 장안구,정자1동,33277,16281,16996,33382,16341,17041,105,60,45
1203,4111157200,2024-09,경기도,수원시 장안구,정자2동,38477,18844,19633,38503,18857,19646,26,13,13
1204,4111157300,2024-09,경기도,수원시 장안구,정자3동,39093,19542,19551,39054,19531,19523,-39,-11,-28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1798,4183037000,2024-09,경기도,양평군,청운면,3751,1944,1807,3748,1938,1810,-3,-6,3
1799,4183038000,2024-09,경기도,양평군,양동면,4529,2292,2237,4518,2286,2232,-11,-6,-5
1800,4183039500,2024-09,경기도,양평군,지평면,6715,3426,3289,6688,3411,3277,-27,-15,-12
1801,4183040000,2024-09,경기도,양평군,용문면,18762,9432,9330,18720,9414,9306,-42,-18,-24
1802,4183041000,2024-09,경기도,양평군,개군면,5115,2613,2502,5100,2606,2494,-15,-7,-8

In [14]:
data.columns

Index(['행정기관코드', '기준연월', '시도명', '시군구명', '읍면동명', '전체 전월인구수', '전월 남자인구수',
       '전월 여자인구수', '전체 당월인구수', '당월 남자인구수', '당월 여자인구수', '전체 인구증감', '남자 인구증감',
       '여자 인구증감'],
      dtype='object')

In [15]:
data = data.drop(['시도명',  '전체 전월인구수', '전월 남자인구수',
       '전월 여자인구수', '전체 당월인구수', '당월 남자인구수', '당월 여자인구수'], axis=1)

In [16]:
data

          행정기관코드     기준연월     시군구명  읍면동명  전체 인구증감  남자 인구증감  여자 인구증감
1200  4111156000  2024-09  수원시 장안구   파장동      -80      -49      -31
1201  4111156600  2024-09  수원시 장안구   율천동       20       13        7
1202  4111157100  2024-09  수원시 장안구  정자1동      105       60       45
1203  4111157200  2024-09  수원시 장안구  정자2동       26       13       13
1204  4111157300  2024-09  수원시 장안구  정자3동      -39      -11      -28
...          ...      ...      ...   ...      ...      ...      ...
1798  4183037000  2024-09      양평군   청운면       -3       -6        3
1799  4183038000  2024-09      양평군   양동면      -11       -6       -5
1800  4183039500  2024-09      양평군   지평면      -27      -15      -12
1801  4183040000  2024-09      양평군   용문면      -42      -18      -24
1802  4183041000  2024-09      양평군   개군면      -15       -7       -8

[603 rows x 7 columns]

In [17]:
data['통합주소'] = data['시군구명'] + " " + data['읍면동명']
data

,행정기관코드,기준연월,시군구명,읍면동명,전체 인구증감,남자 인구증감,여자 인구증감,통합주소
1200,4111156000,2024-09,수원시 장안구,파장동,-80,-49,-31,수원시 장안구 파장동
1201,4111156600,2024-09,수원시 장안구,율천동,20,13,7,수원시 장안구 율천동
1202,4111157100,2024-09,수원시 장안구,정자1동,105,60,45,수원시 장안구 정자1동
1203,4111157200,2024-09,수원시 장안구,정자2동,26,13,13,수원시 장안구 정자2동
1204,4111157300,2024-09,수원시 장안구,정자3동,-39,-11,-28,수원시 장안구 정자3동
...,...,...,...,...,...,...,...,...
1798,4183037000,2024-09,양평군,청운면,-3,-6,3,양평군 청운면
1799,4183038000,2024-09,양평군,양동면,-11,-6,-5,양평군 양동면
1800,4183039500,2024-09,양평군,지평면,-27,-15,-12,양평군 지평면
1801,4183040000,2024-09,양평군,용문면,-42,-18,-24,양평군 용문면
1802,4183041000,2024-09,양평군,개군면,-15,-7,-8,양평군 개군면

In [18]:
data.columns

Index(['행정기관코드', '기준연월', '시군구명', '읍면동명', '전체 인구증감', '남자 인구증감', '여자 인구증감',
       '통합주소'],
      dtype='object')

In [19]:
data = data[['행정기관코드', '기준연월', '시군구명', '읍면동명', '통합주소', '전체 인구증감', '남자 인구증감', '여자 인구증감']]
data

,행정기관코드,기준연월,시군구명,읍면동명,통합주소,전체 인구증감,남자 인구증감,여자 인구증감
1200,4111156000,2024-09,수원시 장안구,파장동,수원시 장안구 파장동,-80,-49,-31
1201,4111156600,2024-09,수원시 장안구,율천동,수원시 장안구 율천동,20,13,7
1202,4111157100,2024-09,수원시 장안구,정자1동,수원시 장안구 정자1동,105,60,45
1203,4111157200,2024-09,수원시 장안구,정자2동,수원시 장안구 정자2동,26,13,13
1204,4111157300,2024-09,수원시 장안구,정자3동,수원시 장안구 정자3동,-39,-11,-28
...,...,...,...,...,...,...,...,...
1798,4183037000,2024-09,양평군,청운면,양평군 청운면,-3,-6,3
1799,4183038000,2024-09,양평군,양동면,양평군 양동면,-11,-6,-5
1800,4183039500,2024-09,양평군,지평면,양평군 지평면,-27,-15,-12
1801,4183040000,2024-09,양평군,용문면,양평군 용문면,-42,-18,-24
1802,4183041000,2024-09,양평군,개군면,양평군 개군면,-15,-7,-8

In [25]:
data['행정기관코드'] = data['행정기관코드'].astype(np.int64)

In [26]:
data['행정기관코드'].dtype

dtype('int64')

In [27]:
df = pd.DataFrame(data)

In [28]:
# 저장할 경로 수정
output_dir = "C:/fintech_service/Project/data/전처리"
output_file = "성별_주민등록_인구증감_전처리.csv"

# 폴더가 존재하지 않으면 생성
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

# 데이터프레임을 CSV 파일로 저장
df.to_csv(os.path.join(output_dir, output_file), index=False, encoding="utf-8-sig")